name: agronomo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+20000

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #BASE
  intl: ^0.17.0
  shared_preferences: '2.0.5'
  package_info: ^2.0.0
  url_launcher: ^6.0.2
  
  #FIREBASE
  google_mobile_ads: ^0.11.0+4

  #UI
  font_awesome_flutter: ^9.0.0
  intro_slider: ^2.3.4
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  flutter_native_splash: ^1.1.4+1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/icon.png
  color: "#1b5e20"
  fullscreen: false

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - lang/it.json
    - lang/en.json

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf