name: agronomo
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+20000

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #BASE
  flutter_launcher_icons: ^0.8.0
  intl: ^0.16.1
  shared_preferences: '>=0.5.12 <2.0.0'
  package_info: ^0.4.3
  url_launcher: ^5.7.2

  #FIREBASE
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_admob: ^0.10.0+2

  #UI
  flutter_native_splash: ^0.1.9
  font_awesome_flutter: ^8.8.1
  intro_slider: ^2.3.3
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/icon.png
  color: "#1b5e20"
  android_disable_fullscreen: false

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - lang/it.json
    - lang/en.json

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Black.ttf
        - asset: assets/fonts/Rubik-BlackItalic.ttf
        - asset: assets/fonts/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik-BoldItalic.ttf
        - asset: assets/fonts/Rubik-Italic.ttf
        - asset: assets/fonts/Rubik-Light.ttf
        - asset: assets/fonts/Rubik-LightItalic.ttf
        - asset: assets/fonts/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik-MediumItalic.ttf
        - asset: assets/fonts/Rubik-Regular.ttf